package com.hnqj.model;

import java.math.BigDecimal;

public class Advert {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert.adposition
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String adposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advert.adprice
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private BigDecimal adprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert.uid
     *
     * @return the value of tb_advert.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert.uid
     *
     * @param uid the value for tb_advert.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert.adposition
     *
     * @return the value of tb_advert.adposition
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getAdposition() {
        return adposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert.adposition
     *
     * @param adposition the value for tb_advert.adposition
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setAdposition(String adposition) {
        this.adposition = adposition == null ? null : adposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advert.adprice
     *
     * @return the value of tb_advert.adprice
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public BigDecimal getAdprice() {
        return adprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advert.adprice
     *
     * @param adprice the value for tb_advert.adprice
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setAdprice(BigDecimal adprice) {
        this.adprice = adprice;
    }
}