package com.hnqj.model;

import java.util.Date;

public class Cashrecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cashrecord.cashuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String cashuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cashrecord.applypeople
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String applypeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cashrecord.applytime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date applytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cashrecord.applynum
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Long applynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cashrecord.checkpeople
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String checkpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cashrecord.checktime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cashrecord.cashstate
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String cashstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cashrecord.cashuid
     *
     * @return the value of tb_cashrecord.cashuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getCashuid() {
        return cashuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cashrecord.cashuid
     *
     * @param cashuid the value for tb_cashrecord.cashuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setCashuid(String cashuid) {
        this.cashuid = cashuid == null ? null : cashuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cashrecord.applypeople
     *
     * @return the value of tb_cashrecord.applypeople
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getApplypeople() {
        return applypeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cashrecord.applypeople
     *
     * @param applypeople the value for tb_cashrecord.applypeople
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setApplypeople(String applypeople) {
        this.applypeople = applypeople == null ? null : applypeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cashrecord.applytime
     *
     * @return the value of tb_cashrecord.applytime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cashrecord.applytime
     *
     * @param applytime the value for tb_cashrecord.applytime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cashrecord.applynum
     *
     * @return the value of tb_cashrecord.applynum
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Long getApplynum() {
        return applynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cashrecord.applynum
     *
     * @param applynum the value for tb_cashrecord.applynum
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setApplynum(Long applynum) {
        this.applynum = applynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cashrecord.checkpeople
     *
     * @return the value of tb_cashrecord.checkpeople
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getCheckpeople() {
        return checkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cashrecord.checkpeople
     *
     * @param checkpeople the value for tb_cashrecord.checkpeople
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setCheckpeople(String checkpeople) {
        this.checkpeople = checkpeople == null ? null : checkpeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cashrecord.checktime
     *
     * @return the value of tb_cashrecord.checktime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cashrecord.checktime
     *
     * @param checktime the value for tb_cashrecord.checktime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cashrecord.cashstate
     *
     * @return the value of tb_cashrecord.cashstate
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getCashstate() {
        return cashstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cashrecord.cashstate
     *
     * @param cashstate the value for tb_cashrecord.cashstate
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setCashstate(String cashstate) {
        this.cashstate = cashstate == null ? null : cashstate.trim();
    }
}