package com.hnqj.model;

import java.util.Date;

public class Playimg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.playuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String playuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.createtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_playimg.imgurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.playuid
     *
     * @return the value of tb_playimg.playuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getPlayuid() {
        return playuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.playuid
     *
     * @param playuid the value for tb_playimg.playuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setPlayuid(String playuid) {
        this.playuid = playuid == null ? null : playuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.createtime
     *
     * @return the value of tb_playimg.createtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.createtime
     *
     * @param createtime the value for tb_playimg.createtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_playimg.imgurl
     *
     * @return the value of tb_playimg.imgurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_playimg.imgurl
     *
     * @param imgurl the value for tb_playimg.imgurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}