package com.hnqj.model;

import java.math.BigDecimal;
import java.util.Date;

public class Releaseadvert {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.aduid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String aduid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.adpositionid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String adpositionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.adprice
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private BigDecimal adprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.imgurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.createtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.clickcount
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String clickcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.clientuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String clientuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.aduid
     *
     * @return the value of tb_releaseadvert.aduid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getAduid() {
        return aduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.aduid
     *
     * @param aduid the value for tb_releaseadvert.aduid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setAduid(String aduid) {
        this.aduid = aduid == null ? null : aduid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.adpositionid
     *
     * @return the value of tb_releaseadvert.adpositionid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getAdpositionid() {
        return adpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.adpositionid
     *
     * @param adpositionid the value for tb_releaseadvert.adpositionid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setAdpositionid(String adpositionid) {
        this.adpositionid = adpositionid == null ? null : adpositionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.adprice
     *
     * @return the value of tb_releaseadvert.adprice
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public BigDecimal getAdprice() {
        return adprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.adprice
     *
     * @param adprice the value for tb_releaseadvert.adprice
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setAdprice(BigDecimal adprice) {
        this.adprice = adprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.imgurl
     *
     * @return the value of tb_releaseadvert.imgurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.imgurl
     *
     * @param imgurl the value for tb_releaseadvert.imgurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.createtime
     *
     * @return the value of tb_releaseadvert.createtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.createtime
     *
     * @param createtime the value for tb_releaseadvert.createtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.clickcount
     *
     * @return the value of tb_releaseadvert.clickcount
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getClickcount() {
        return clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.clickcount
     *
     * @param clickcount the value for tb_releaseadvert.clickcount
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setClickcount(String clickcount) {
        this.clickcount = clickcount == null ? null : clickcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.clientuid
     *
     * @return the value of tb_releaseadvert.clientuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getClientuid() {
        return clientuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.clientuid
     *
     * @param clientuid the value for tb_releaseadvert.clientuid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setClientuid(String clientuid) {
        this.clientuid = clientuid == null ? null : clientuid.trim();
    }
}