package com.hnqj.model;

public class Sysusermgr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.fid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.fname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.birthday
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.ethnic
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String ethnic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.idcard
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.officephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String officephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.mobilephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.email
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.sex
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.pinyin
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.isdel
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Short isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.qq
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.weixin
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.userno
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.familyphone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String familyphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.familyaddress
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String familyaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sysusermgr.extrainfo
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String extrainfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.fid
     *
     * @return the value of tb_sysusermgr.fid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.fid
     *
     * @param fid the value for tb_sysusermgr.fid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.fname
     *
     * @return the value of tb_sysusermgr.fname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.fname
     *
     * @param fname the value for tb_sysusermgr.fname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.birthday
     *
     * @return the value of tb_sysusermgr.birthday
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.birthday
     *
     * @param birthday the value for tb_sysusermgr.birthday
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.state
     *
     * @return the value of tb_sysusermgr.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.state
     *
     * @param state the value for tb_sysusermgr.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.ethnic
     *
     * @return the value of tb_sysusermgr.ethnic
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getEthnic() {
        return ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.ethnic
     *
     * @param ethnic the value for tb_sysusermgr.ethnic
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setEthnic(String ethnic) {
        this.ethnic = ethnic == null ? null : ethnic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.idcard
     *
     * @return the value of tb_sysusermgr.idcard
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.idcard
     *
     * @param idcard the value for tb_sysusermgr.idcard
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.officephone
     *
     * @return the value of tb_sysusermgr.officephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getOfficephone() {
        return officephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.officephone
     *
     * @param officephone the value for tb_sysusermgr.officephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setOfficephone(String officephone) {
        this.officephone = officephone == null ? null : officephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.mobilephone
     *
     * @return the value of tb_sysusermgr.mobilephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.mobilephone
     *
     * @param mobilephone the value for tb_sysusermgr.mobilephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.email
     *
     * @return the value of tb_sysusermgr.email
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.email
     *
     * @param email the value for tb_sysusermgr.email
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.sex
     *
     * @return the value of tb_sysusermgr.sex
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.sex
     *
     * @param sex the value for tb_sysusermgr.sex
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.pinyin
     *
     * @return the value of tb_sysusermgr.pinyin
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.pinyin
     *
     * @param pinyin the value for tb_sysusermgr.pinyin
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.isdel
     *
     * @return the value of tb_sysusermgr.isdel
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Short getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.isdel
     *
     * @param isdel the value for tb_sysusermgr.isdel
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setIsdel(Short isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.qq
     *
     * @return the value of tb_sysusermgr.qq
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.qq
     *
     * @param qq the value for tb_sysusermgr.qq
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.weixin
     *
     * @return the value of tb_sysusermgr.weixin
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.weixin
     *
     * @param weixin the value for tb_sysusermgr.weixin
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.userno
     *
     * @return the value of tb_sysusermgr.userno
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.userno
     *
     * @param userno the value for tb_sysusermgr.userno
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.familyphone
     *
     * @return the value of tb_sysusermgr.familyphone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getFamilyphone() {
        return familyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.familyphone
     *
     * @param familyphone the value for tb_sysusermgr.familyphone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setFamilyphone(String familyphone) {
        this.familyphone = familyphone == null ? null : familyphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.familyaddress
     *
     * @return the value of tb_sysusermgr.familyaddress
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getFamilyaddress() {
        return familyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.familyaddress
     *
     * @param familyaddress the value for tb_sysusermgr.familyaddress
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setFamilyaddress(String familyaddress) {
        this.familyaddress = familyaddress == null ? null : familyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sysusermgr.extrainfo
     *
     * @return the value of tb_sysusermgr.extrainfo
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getExtrainfo() {
        return extrainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sysusermgr.extrainfo
     *
     * @param extrainfo the value for tb_sysusermgr.extrainfo
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setExtrainfo(String extrainfo) {
        this.extrainfo = extrainfo == null ? null : extrainfo.trim();
    }
}