package com.hnqj.model;

import java.util.Date;

public class Train {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.teruid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String teruid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.trainname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String trainname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.traintime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date traintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.trainaddress
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String trainaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.phone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.logoimg
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String logoimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.topflag
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String topflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.price
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.delflag
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.legtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Date legtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.teruid
     *
     * @return the value of tb_train.teruid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getTeruid() {
        return teruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.teruid
     *
     * @param teruid the value for tb_train.teruid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setTeruid(String teruid) {
        this.teruid = teruid == null ? null : teruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.trainname
     *
     * @return the value of tb_train.trainname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getTrainname() {
        return trainname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.trainname
     *
     * @param trainname the value for tb_train.trainname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setTrainname(String trainname) {
        this.trainname = trainname == null ? null : trainname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.traintime
     *
     * @return the value of tb_train.traintime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getTraintime() {
        return traintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.traintime
     *
     * @param traintime the value for tb_train.traintime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setTraintime(Date traintime) {
        this.traintime = traintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.trainaddress
     *
     * @return the value of tb_train.trainaddress
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getTrainaddress() {
        return trainaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.trainaddress
     *
     * @param trainaddress the value for tb_train.trainaddress
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setTrainaddress(String trainaddress) {
        this.trainaddress = trainaddress == null ? null : trainaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.phone
     *
     * @return the value of tb_train.phone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.phone
     *
     * @param phone the value for tb_train.phone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.logoimg
     *
     * @return the value of tb_train.logoimg
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getLogoimg() {
        return logoimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.logoimg
     *
     * @param logoimg the value for tb_train.logoimg
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setLogoimg(String logoimg) {
        this.logoimg = logoimg == null ? null : logoimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.topflag
     *
     * @return the value of tb_train.topflag
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getTopflag() {
        return topflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.topflag
     *
     * @param topflag the value for tb_train.topflag
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setTopflag(String topflag) {
        this.topflag = topflag == null ? null : topflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.price
     *
     * @return the value of tb_train.price
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.price
     *
     * @param price the value for tb_train.price
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.delflag
     *
     * @return the value of tb_train.delflag
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.delflag
     *
     * @param delflag the value for tb_train.delflag
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.legtime
     *
     * @return the value of tb_train.legtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Date getLegtime() {
        return legtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.legtime
     *
     * @param legtime the value for tb_train.legtime
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setLegtime(Date legtime) {
        this.legtime = legtime;
    }
}