package com.hnqj.model;

public class UserinfoWithBLOBs extends Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.idpic
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String idpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.idpicback
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String idpicback;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.idpic
     *
     * @return the value of tb_userinfo.idpic
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getIdpic() {
        return idpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.idpic
     *
     * @param idpic the value for tb_userinfo.idpic
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setIdpic(String idpic) {
        this.idpic = idpic == null ? null : idpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.idpicback
     *
     * @return the value of tb_userinfo.idpicback
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getIdpicback() {
        return idpicback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.idpicback
     *
     * @param idpicback the value for tb_userinfo.idpicback
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setIdpicback(String idpicback) {
        this.idpicback = idpicback == null ? null : idpicback.trim();
    }
}